etl_config:
  # Google Drive Dataset URL
  dataset_url: "https://drive.google.com/file/d/139OEjxiFwxJtFQWaixF0fG4JSQyGp6EP/view?usp=sharing"
  database_name: database

  # Directory for downloading and extracting data
  archive_dir: "/workspaces/Data-Wharehouse-ETL/database/archive"
  extracted_dir: "/workspaces/Data-Wharehouse-ETL/database/sql"

  # Database paths
  db_path: "/workspaces/Data-Wharehouse-ETL/data/extracted/database.sqlite"
  query: "SELECT * FROM otp"

  csv_data: "/workspaces/Data-Wharehouse-ETL/database/csv_data"
  # Output directory 
  data_wharesave: "/workspaces/Data-Wharehouse-ETL/database/trasformer_data"
  analysis_report_path: "/workspaces/Data-Wharehouse-ETL/database/trasformer_data"

  # Files for visualization
  avg_delay_file: "/workspaces/Data-Wharehouse-ETL/database/trasformer_data/delay_summary.csv"
  train_status_file: "/workspaces/Data-Wharehouse-ETL/database/trasformer_data/df.csv"
  visualize_output_dir: "/workspaces/Data-Wharehouse-ETL/visualize"